name: Build

on:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7' 
          
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - name: Build
        run: |
          rm ./dist/*
          cp ./edit/* ./
          rm package-lock.json yarn.lock
          yarn
          yarn build
                    
      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: dist
          path: ./dist
