name: Build

on:
  workflow_dispatch:
jobs:
  build:
    if: github.repository_owner == github.actor
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          
      - name: Build
        run: |
          rm ./dist/*
          cp ./edit/* ./
          rm package-lock.json yarn.lock
          npm install -g gulp
          npm install
          gulp style
                    
      - name: upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: dist
          path: ./dist
